### ISSUE TITLE
Please add more documentation

### ISSUE THREAD

**Issue by jkrick** [fkiwy/unTimely_Catalog_explorer#1]
1.. Please add a description of how to install your code.  Currently I am using the following, but this took me a while to figure out.
`try:
    from unTimely_Catalog_tools import unTimelyCatalogExplorer
except ImportError:
    if not os.path.exists('./unTimely_Catalog_explorer'):
        !git clone https://github.com/fkiwy/unTimely_Catalog_explorer.git
    sys.path.append('./unTimely_Catalog_explorer')
    from unTimely_Catalog_tools import unTimelyCatalogExplorer
`

2. Please add more result_table documentation.  It's not clear to me what is returned in the result_table from `search_by_coordinates`.  Example questions I have are what are many of the columns? why information are we getting by using eg., '1.1' in the object_label? What unit of flux is nMgy? what is 'dflux'? what is 'nm'? and I'm guessing you are returning one row per observation, then can we assume that 'epoch' 1 - 16 would be the full light curve for a single object even though they don't have the same 'object_label' or 'ra, dec'?

3. For the functions which return plots or images, it took me a long time to figure out that they are being saved in /tmp.  Please add that info for other potential users.

**Comment by fkiwy** [comment]
> Please add a description of how to install your code.

I added a setup.py file.
The code can now be installed as follows:
```
git clone https://github.com/fkiwy/unTimely_Catalog_explorer.git
cd unTimely_Catalog_explorer
python setup.py install
```

> Please add more result_table documentation. It's not clear to me what is returned in the result_table from ``search_by_coordinates``.

The column description is included in the result table returned by ``search_by_coordinates`` and can be displayed as follows: ``print(result_table.info)``
I added the description to the README.md file.

> I'm guessing you are returning one row per observation, then can we assume that 'epoch' 1 - 16 would be the full light curve for a single object even though they don't have the same 'object_label' or 'ra, dec'?

Yes, exactly. Although ``object_label`` is somewhat misleading. I renamed it to ``source_label``, it refers to a single unTimely detection. Detections are not related in any way across epochs (neither by ``source_label``, nor by ``unwise_detid``, or ``ra`` and ``dec``). The ``source_label`` can be used to retrieve the corresponding source on the finder charts if ``overlay_labels=True`` has been specified with the ``create_finder_charts`` method.

> For the functions which return plots or images, it took me a long time to figure out that they are being saved in /tmp.

I added this info to the README.md file.
