### ISSUE TITLE
remove printed output

### ISSUE THREAD

**Issue by jkrick** [fkiwy/unTimely_Catalog_explorer#2]
Can you please either remove the printed output or add a verbose flag.  Trying to run this in a loop for even a few objects makes a lot of unnecessary (for me) output on the screen.

**Comment by fkiwy** [comment]
I added a parameter to the unTimelyCatalogExplorer constructor allowing you to suppress all console output except error messages: ``suppress_console_output=True``
```python
ucx = unTimelyCatalogExplorer(directory='unTimely_Catalog_tools_output', cache=False, show_progress=True,
                              timeout=300, suppress_console_output=True,
                              catalog_base_url='http://unwise.me/data/neo7/untimely-catalog/',
                              catalog_index_file='untimely_index-neo7.fits')
```
