### ISSUE TITLE
Question: How to query by unwise_detid? 

### ISSUE THREAD

**Issue by rdrimmel** [fkiwy/unTimely_Catalog_explorer#4]
(Sorry, I see no other way to submit questions.) 

Is there not a method to search by unwise_detid?   I already know for which unWISE sources I wish to have the epoch photometry.

**Comment by fkiwy** [comment]
Currently, the catalog can only be searched by coordinates.
(I'm fine with submitting questions here, so no need to apologize for that.)

**Comment by rdrimmel** [comment]
Should I make a change request?  ;^)

**Comment by fkiwy** [comment]
Please note that the unwise_objid from the unWISE catalog (Schlafly+2019) is not the same than the unwise_detid from the unTimely catalog. The unwise_detid from the unTimely catalog refers to a single detection whereas the unwise_objid from the unWISE catalog refers to an object/source. unTimely detections and unWISE objects are not related in any way. Also, unTimely detections are not related in any way across epochs. So, the only way to get epoch photometry for an object is to search the unTimely catalog by coordinates and inspect the result table together with the finder charts (overlay_labels=True) to reliably assign detections to a specific source. The overlay labels match the source labels (source_label column) in the result table.

**Comment by rdrimmel** [comment]
Dear Frank,

Thanks for the clarification. Very helpful.

Ron
