### ISSUE TITLE
Missing requests requirement in setup.py

### ISSUE THREAD

**Issue by jgagneastro** [fkiwy/unTimely_Catalog_explorer#6]
The install_requires in setup.py is missing the requests package

**Comment by fkiwy** [comment]
The 'requests' package is not explicitly used by unTimely_Catalog_explorer. It may be used implicitly, i.e. by one of the unTimely_Catalog_explorer direct dependencies, but should then be present in the requirements.txt file of the corresponding dependency and therefore installed automatically.
